
<?php 
	#include Controller of the project
	/*
	*
	* Controller handles the all request of which is generated by the user activity in the 
	* project 
	*/
	
	require('Controller.php');
?>
<html>
	<head>
		<title>RTCamp Twitter Demo</title>
		<?php
			#include Config file
			/*
			*
			* include configuration of JS,Bootstrap ,JQuery,custome css - js,font 
			*/
			require('config.php');
		?>
	</head>
	<body>
		<div class="text-center" id= "body">
		<?php 

			if(isset($_SESSION['login_url']) && !isset($_SESSION['data'])){
				$login_url = $_SESSION['login_url'];
			?>
			<div class= "login-btn">
				<a href='<?php echo $login_url; ?>'>
					<button type="button" class="btn btn-primary btn-md">
		        	<i class="fa fa-twitter"></i>
				    | Login With Twitter
				    </button>
	        	</a>
			</div>
				
			<?php
			}else{
				header('Location:home.php');
			}
		?>
		</div>
		
	</body>
</html>
